print("----------------");
print("----Variebles numericas---");
#Ln_Valor=int(input("ingrese valor #1:"));
#print(Ln_Valor * 3);
#print("Cuantos dias quieres libre:" + str(Ln_Valor));
print("--------Conversion de tipos--------");
print("Todos los dias es lunes.\n");
print("Todos los dias es martes.\n");
print("Todos los dias es viernes.\n");
print("----------------");
print("Ingrese 's' para continuar.");
print('Ingrese "s" para continuar.');
print("----------------");
Lv_Nombre=input("Ingrese nombre:");
Lv_Apellido=input("Ingrese apellido:");
print("Su nombre en mayuscula:", Lv_Nombre.upper());
print("Su apellido en mayuscula:", Lv_Apellido.lower());
print("----------------");
print("Su apellido tiene un total de:", len(Lv_Apellido));
print("----------------");
Lv_Frase1=input("Ingrese frase:");
print("Dentro de su frace existe 'a':",Lv_Frase1.count('a'));
print("Dentro de su frace existe 'a':",Lv_Frase1.count('A'));
print("Esta es su frase si reemplazamos la 'a'por la 'e':",Lv_Frase1.replace('a','e'));
print(f"La frase ingresada es:{Lv_Frase1}");
print("------------------------");
print("La subfrase 'ta' ¿Existe dentro de la frase?",'ta'in Lv_Frase1);
print("------------------------");
print("La subfrase 'ta' ¿No Existe dentro de la frase?",'ta' not in Lv_Frase1);